import { FC } from 'react';
import styles from '../../styles/Home.module.css';
import Head from 'next/head';
import { Hamburger } from '@/components/Menu/Hamburger';

type PropTypes = {
  children?: React.ReactNode;
};

export const Layout: FC<PropTypes> = ({ children }) => (
  <div className={styles.main}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <Hamburger />
    {children}
  </div>
);
